# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-28 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyas2', '0021_auto_20190329_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='extra_headers',
            field=models.TextField(null=True),
        ),
    ]
